FROM node:20-alpine
WORKDIR /app
ENV VITE_HOST=0.0.0.0
ENV CHOKIDAR_USEPOLLING=true
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
